### PR TITLE
Fix for GHC 9.2.2

### PR DESCRIPTION
**Pull request by cydparser**

### CODE REVIEW

**Comment by cydparser** [comment]
@andreasabel would you mind merging this?

**Comment by andreasabel** [comment]
@cydparse: Atm, we cannot re-release, because @bos is the only uploader: https://hackage.haskell.org/package/text-format/maintainers/
Do you want to takeover the package?  I suppose you have to go through the usual takeover process unless you can reach Bryan O'Sullivan.

**Comment by hesselink** [comment]
@andreasabel You should be able to do a non maintainer upload as detailed in https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#3-source-changes-simple-patches, right? Let me know if you need me to temporarily add you as a maintainer.

@cydparser If you want to take over the package, let me know as well and I can help with that (hackage-admin@haskell.org).

**Comment by phadej** [comment]
I'd recommend migrating to use e.g. https://hackage.haskell.org/package/formatting, if no-one is willing to properly take over and maintain `text-format`. I'm not convinced that Hackage Trustees need to spend time any more time on `text-format`. We did NMU in 2018, that's four years ago. (Back then liquid haskell used `text-format`, nowadays it doesn't).

**Comment by cydparser** [comment]
I'll check out `formatting`, thanks. What does NMU mean?

**Comment by phadej** [comment]
NMU is non maintainer upload

**Comment by andreasabel** [comment]
@hesselink : Thanks for chiming in.  Personally, I do not bother with charity NMUs.  But if you want to add me as uploader to `text-format`, I can look into fixing this issue.

Also, I think that the `haskell` organization should take care that its packages are in good shape.  This package should not have to sit on `hackage-trustees`. (You do not seem to be part of the `haskell` organization though, at least I could not find you on https://github.com/orgs/haskell/people . Otherwise you could maybe have helped getting this package in order there...)

**Comment by hesselink** [comment]
@andreasabel Not sure what 'charity NMUs' are, but I've added you as a temporary maintainer to `text-format`. As for my role, I don't write Haskell professionally anymore, and therefore am less active in the Haskell community. However, I am still happy to help as hackage admin, so I can add maintainers for NMUs and package takeover.

**Comment by andreasabel** [comment]
Ok, I released this as 0.3.2.1.

@hesselink Erik, thanks for adding me as uploader.
I suppose you keep me there, since a package isn't well off without a maintainer.

**Pull request merged**
